version: "2"
services:

  crushftp:
    image: crush
    ports:
      - "2222:2222"   # sftp
      - "80:80" # http backup port
      - "443:443" # https
    environment:
      FTPADMINPASSWORD: admin
    volumes:
      - /a/data/webftp.adito.de/:/var/opt/CrushFTP8_PC/
      - /a/data/webftp.adito.des/share:/share/
      #- /a/data/webftp.adito.de/adito.png:/var/opt/CrushFTP8_PC/WebInterface/images/adito.png:rw
    restart: unless-stopped
